project:
  type: website

website:
  title: "GitClub"
  navbar:
    right:
      - stepone.qmd
      - steptwo.qmd
      - stepthree.qmd
      - stepfour.qmd
  page-footer: 
    left: "Web Development: Utilizing Quarto To Create A Website"
format:
  html:
    theme: solar
    css: styles.css

editor: visual

